### ISSUE TITLE
Roles not applying 

### ISSUE THREAD

**Issue by JulesR2** [alterphp/EasyAdminExtensionBundle#109] opened 2019-03-14 18:44 UTC
Symfony 4.2.4, seems like roles for entities work but it doesn't for properties.
E.g. this works

```
Cat:
    class: App\Entity\Cat
    role: ROLE_ADMIN
```

but following does not apply
```
Post:
    class: App\Entity\Post
    controller: App\Controller\AdminController
    list:
        fields:
            - { property: 'visible', role: ROLE_ADMIN }
```

(checked in debugger, roles for the current user are OK)

**Comment by ArminVieweg** [comment] 2019-03-23 20:36
**It is even worse!!!** Even when you define the role for the whole entity or for all actions seperately, **it just removes icons**. You can still access edit or new action, when you know query parameters.

But I think this is more a missing feature, rather a bug. But when you think you are secure: you are not!

**Comment by ArminVieweg** [comment] 2019-03-23 20:41
@JulesR2 Btw. I've tested role at a field. It works on edit form (makes the field disabled and ignores is on submit). It does not apply in list view.

**Comment by alterphp** [comment] 2019-04-03 12:25
Hi @JulesR2 !

What you mention is not a bug but a requested feature ;-) As @ArminVieweg told, it's not intended to affect columns in a list...

But this could be a nice feature ! Interested in working on it ?

**Comment by JulesR2** [comment] 2019-04-03 12:50
Hi all, sorry for late reply. Didn't know that it does not apply to list, but could be great indeed

**Comment by alterphp** [comment] 2019-04-16 07:45
Closing as it's no bug but a non existent feature

**Closed by alterphp** 2019-04-16 07:45 UTC
Labels: enhancement, todo
